import type { Metadata } from "next";
import { Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import client from "@/tina/__generated__/client";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap"
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const navigationItems = [
  {
    name: "Storitve",
    href: "/storitve",
    subItems: [
      { name: "Splošna zobozdravstvo", href: "/storitve/splosna" },
      { name: "Ortodontija", href: "/storitve/ortodontija" },
      { name: "Implantologija", href: "/storitve/implantologija" },
      { name: "Estetska zobozdravstvo", href: "/storitve/estetska" }
    ]
  },
  {
    name: "Informacije",
    subItems: [
      { name: "O nas", href: "/o-nas" },
      { name: "Cenik", href: "/cenik" },
      { name: "Pogosta vprašanja", href: "/faq" }
    ]
  }
];

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locationsResponse = await client.queries.locationConnection();
  const locations =
    locationsResponse.data.locationConnection.edges?.map((edge) => {
      const node = edge?.node;
      return {
        officeHours: node?.officeHours || null,
        phone: node?.phone?.filter((p): p is string => p !== null) || [],
        googleMapsEmbedSrc: node?.googleMapsEmbedSrc || "",
        name: node?.label || "",
        email: node?.mail || ""
      };
    }) || [];

  return (
    <html
      data-theme="mytheme"
      lang="en"
      className={`${montserrat.variable} ${playfairDisplay.variable} antialiased`}
    >
      <body className="font-montserrat min-h-dvh flex flex-col">
        <Navbar items={navigationItems}></Navbar>
        <div className="grow mt-20">{children}</div>
        <Footer locations={locations} />
      </body>
    </html>
  );
}
