import type { Metadata } from "next";
import { Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap"
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const navigationItems = [
  {
    name: "Storitve",
    href: "/storitve",
    subItems: [
      { name: "Splošna zobozdravstvo", href: "/storitve/splosna" },
      { name: "Ortodontija", href: "/storitve/ortodontija" },
      { name: "Implantologija", href: "/storitve/implantologija" },
      { name: "Estetska zobozdravstvo", href: "/storitve/estetska" }
    ]
  },
  {
    name: "Informacije",
    href: "/informacije",
    subItems: [
      { name: "O nas", href: "/o-nas" },
      { name: "Cenik", href: "/cenik" },
      { name: "Pogosta vprašanja", href: "/faq" }
    ]
  }
];

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${playfairDisplay.variable} antialiased`}
    >
      <body className="font-montserrat">
        <Navbar items={navigationItems} />
        {children}
      </body>
    </html>
  );
}
